name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests
      run: |
        pytest tests --headless --junit-xml=reports/results.xml 

    - name: Send Test Results to TestIT
      run: |
        testit results import \
          --url https://team-pqbi.testit.software \
          --project-id 01974f80-3197-7392-a7eb-4e3abc3ec774 \
          --configuration-id 01974f80-31d0-756b-bac2-cdda5de0f631 \
          --testrun-name "Pytest test run" \
          --results reports \
          --token ${{ secrets.TMS_TOKEN }}
      env:
        TMS_TOKEN: ${{ secrets.TMS_TOKEN }}